#pragma once

// GENERATED by scripts/generate_config.py from targets/botw.json.
// Do not edit; edit the target.

namespace WiiXLaunch::Host {
    // Which target this host was built as. Logged at boot, so a subsdk9 on an
    // SD card can say what it is rather than being identified by its date.
    constexpr char TargetName[]  = "botw";
    constexpr char ProjectName[] = "WiiXLaunch_BotW";

    // Uppercase, because that is how Atmosphere spells a title id on disk and
    // the Switch host builds an SD path out of this.
    constexpr char TitleId[]     = "01007EF00011E000";

    // sd:/WiiXLaunch/mods/<TitleId>, which is where this host looks first. One
    // SD card holds every game's modules; a graphic pack and a Wii U content
    // directory are already scoped to their title, and an SD card is not.
    constexpr char ModsDir[]     = "WiiXLaunch/mods/01007EF00011E000";

    // false: declared patches are verified and then RESTORED between LoadAll and
    // RunPhase, so the sample patch mod demonstrates its three outcomes without
    // outliving its own boot.
    // true: they stay, which is what a patch mod is for.
    constexpr bool PatchesPersist = false;
}
