#pragma once

// GENERATED by scripts/generate_config.py from targets/totk.json.
// Do not edit; edit the target.

#include <cstdint>

namespace WiiXLaunch::Host {
    // Which target this host was built as. Logged at boot, so a subsdk9 on an
    // SD card can say what it is rather than being identified by its date.
    constexpr char TargetName[]  = "totk";
    constexpr char ProjectName[] = "WiiXLaunch_TotK";

    // Uppercase, because that is how Atmosphere spells a title id on disk and
    // the Switch host builds an SD path out of this.
    constexpr char TitleId[]     = "0100F2C0115B6000";

    // sd:/WiiXLaunch/mods/<TitleId>, which is where this host looks first. One
    // SD card holds every game's modules; a graphic pack and a Wii U content
    // directory are already scoped to their title, and an SD card is not.
    constexpr char ModsDir[]     = "WiiXLaunch/mods/0100F2C0115B6000";

    // 0 = exl_main, before the game's main.
    // 1 = the first file the game opens, for an SDK whose filesystem is not
    //     usable that early. See the target's //load_point note.
    constexpr int SwitchLoadPoint = 1;
    constexpr char SwitchLoadPointName[] = "fs_ready";

    // false: declared patches are verified and then RESTORED between LoadAll and
    // RunPhase, so the sample patch mod demonstrates its three outcomes without
    // outliving its own boot.
    // true: they stay, which is what a patch mod is for.
    constexpr bool PatchesPersist = true;

    // --- which build of the game is this? --------------------------------
    //
    // The slice the host CRCs to fingerprint the running game, and the builds
    // this target has been told the answer for. Length 0 means this target
    // declares no identity, which the host reports rather than guessing past.
    // See include/wiixlaunch/game_version.hpp.
    constexpr uint32_t IdentitySwitchOffset = 0x00800000;
    constexpr uint32_t IdentitySwitchLength = 4096;
    constexpr uint32_t IdentityWiiuAddress  = 0x00000000;
    constexpr uint32_t IdentityWiiuLength   = 0;

    struct KnownBuild { uint32_t fingerprint; const char* name; };

    // Terminated by a null name. Enrol a build by pasting the fingerprint the
    // host logs into the target's identity.known.
    constexpr KnownBuild KnownSwitchBuilds[] = {
        { 0x3BDA566B, "1.0.0" },
        { 0xC1404ED7, "1.0.1" },
        { 0x975A39A9, "1.1.0" },
        { 0x5ABB81DD, "1.1.1" },
        { 0xC045FF85, "1.1.2" },
        { 0xBFDDB060, "1.2.0" },
        { 0x181D91D8, "1.3.0" },
        { 0x95320A30, "1.4.0" },
        { 0x26C65193, "1.4.1" },
        { 0xEEAD6F44, "1.4.2" },
        { 0x3773378F, "1.4.3" },
        { 0, nullptr },
    };
    constexpr KnownBuild KnownWiiuBuilds[] = {
        { 0, nullptr },
    };
}
