#pragma once

// GENERATED by scripts/generate_config.py from targets/botw.json.
// Do not edit; edit the target.

namespace WiiXLaunch::Host {
    // Which target this host was built as. Logged at boot, so a subsdk9 on an
    // SD card can say what it is rather than being identified by its date.
    constexpr char TargetName[]  = "botw";
    constexpr char ProjectName[] = "WiiXLaunch_BotW";

    // false: declared patches are verified and then RESTORED between LoadAll and
    // RunPhase, so the sample patch mod demonstrates its three outcomes without
    // outliving its own boot.
    // true: they stay, which is what a patch mod is for.
    constexpr bool PatchesPersist = false;
}
