#pragma once

// GENERATED by scripts/generate_config.py from targets/totk.json - do not edit.
//
// The Cemu entry hook, as macros the bootstrap's asm() block can stringify.
// These are the only game-specific values base's bootstrap needs; everything
// else about it is game-agnostic.

#define WIIXL_CEMU_ENTRY_HOOK        0x00000000
#define WIIXL_CEMU_ENTRY_RETURN      0x00000004
#define WIIXL_CEMU_ENTRY_RETURN_HI   0x0000
#define WIIXL_CEMU_ENTRY_RETURN_LO   0x0004
#define WIIXL_CEMU_ENTRY_DISPLACED   0x00000000
