#include <wiixlaunch.hpp>
#include <wiixlaunch/loader/load_point.hpp>
#include <wiixlaunch/game_version.hpp>
#include <wiixlaunch/loader/core_surface.hpp>
#include <wiixlaunch/loader/net_surface.hpp>
#include <wiixlaunch/loader/base_surfaces.hpp>

// --- the game module, whichever one this project installed --------------------
//
// A game module - BotW, or anything else - provides <wiixlaunch/module.hpp>,
// which declares WiiXLaunch::GameModule::Register(). That is a FIXED PATH and a
// fixed name, so this file does not have to know which game it was built for,
// and a tree with no module in vendor/ still compiles.
//
// __has_include rather than a weak symbol, for the reason spelled out at the
// registration call below: deploy.py relocates every ADDR32 site by adding the
// code-cave base, so an undefined weak symbol would resolve to 0, come out as
// g_CodeCaveBase, and test as non-null. This is settled by the preprocessor and
// cannot be fooled that way.
#if __has_include(<wiixlaunch/module.hpp>)
#include <wiixlaunch/module.hpp>
#define WIIXL_HAVE_GAME_MODULE 1
#endif

// The logo demo below is BotW's, not base's: NVN and GX2 come from that module.
// It is sample code and the file says so - delete it and everything above still
// builds. Guarded separately from the module hookup so that a project with a
// DIFFERENT game module is not asked to provide BotW's graphics namespaces.
//
// -DWIIXL_NO_DEMO compiles it out without touching this file, which is what
// you want when bisecting a crash: the demo installs a graphics hook into the
// game's render path, and "is it the demo" should be answerable by rebuilding
// rather than by editing and remembering to put it back.
#if __has_include(<wiixlaunch/botw/botw.hpp>) && !defined(WIIXL_NO_DEMO)
#include <wiixlaunch/botw/botw.hpp>
#define WIIXL_BOTW_DEMO 1
using namespace WiiXLaunch::BotW;
#endif

// feel free to remove this, its just proof your toolchain works end-end -
// the OnRender callbacks here and their registration in WiiXLaunch_Init
// below can both go. The WIIXL_LOG lines in there are the proof-of-life
// that works on every platform.
#if WIIXL_BOTW_DEMO
#if WIIXL_SWITCH
// The texture is COMPILED IN, not read from disk, and that is the difference
// from Cemu worth knowing. Cemu's logo is src/resources/logo.png, packaged to
// logo.bin by scripts/pack_resources.py and loaded at runtime through GX2's
// 16-byte-header format. NVN wants a different container - a 0x200-byte header
// with width at 0x40, height at 0x44 and format at 0x50 - so this one ships as
// a byte array and needs no filesystem at all.
//
// The array was generated by scripts/pack_texture.py, which is NOT in the tree:
// it and every asset header were deleted in db3a207 and 7c4969d as bloat, which
// is defensible - this header alone is 1.6 MB of hex. Both are recoverable:
//
//   git show db3a207^:include/testpic_texture_bytes.hpp
//   git show 7c4969d^:scripts/pack_texture.py
//
// Delete both this include and the block in WiiXLaunch_Init if you want the
// 1.6 MB back; -DWIIXL_NO_DEMO does it without editing anything.
#include <testpic_texture_bytes.hpp>

static NVN::TextureHandle g_LogoTexture = 0;

void OnRender(NVN::CommandBuffer* cmdBuf, void* dstTexture, int width, int height) {
    if (g_LogoTexture) {
        NVN::DrawSprite(cmdBuf, dstTexture, g_LogoTexture, -0.92f, 0.50f, 0.225f, 0.40f);
    }
}
#elif WIIXL_CEMU
static GX2::TextureHandle g_LogoTexture = 0;

void OnRender(GX2::CommandBuffer* cmdBuf, void* dstTexture, int width, int height) {
    if (g_LogoTexture) {
        GX2::DrawSprite(cmdBuf, dstTexture, g_LogoTexture, -0.92f, 0.50f, 0.225f, 0.40f);
    }
}
#elif WIIXL_WIIU
static GX2::TextureHandle g_LogoTexture = 0;

void OnRender(GX2::CommandBuffer* cmdBuf, void* dstTexture, int width, int height) {
    GX2::DrawSprite(cmdBuf, dstTexture, g_LogoTexture, -0.92f, 0.50f, 0.225f, 0.40f);
}
#endif
#endif // WIIXL_BOTW_DEMO


// Entry point called once at plugin/module load. Install your hooks here.
extern "C" void WiiXLaunch_Init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

#if WIIXL_WIIU
    if (!WiiXLaunch::Backend::InitWiiUBackend()) return;
#elif WIIXL_CEMU
    if (!WiiXLaunch::Backend::InitCemuBackend()) return;
#endif

    WIIXL_LOG("WiiXLaunch: init OK");

    // BEFORE ANY HOOK OR PATCH. Every offset below this line was written
    // against one build of the game, and this is the only thing that says
    // which build is actually running. It does not refuse - a host that
    // stopped dead on an unenrolled build would be unusable the day a game
    // updates - but it puts the answer in the log above every address that
    // depends on it.
    WiiXLaunch::GameVersion::Detect();

    // --- STAGE 2: the surface registry --------------------------------------
    //
    // wiixl.core first, then whatever game modules this project installed.
    //
    // Registration is an explicit call, NOT static self-registration. The flat
    // Cemu payload does not run C++ static constructors: scripts/cemu.ld has no
    // .init_array output section, the linked ELF has none at all, and the
    // bootstrap goes straight from relocating to WiiXLaunch_Init without ever
    // walking one. Everything works today only because every global here is POD
    // with a constant initialiser. A module that tried to register itself from
    // a static constructor would simply never run.
    //
    // A weak-symbol hook would be the other obvious way to let base call into
    // modules it cannot name, and it is a trap in THIS codebase specifically:
    // deploy.py relocates every ADDR32 site by adding the code-cave base, so an
    // undefined weak symbol resolving to 0 would come out as g_CodeCaveBase and
    // test as non-null. Explicit calls avoid the whole question.
    WiiXLaunch::Core::Register();

    // wiixl.net is base's too, but SEPARATE, because not every platform can
    // back it. On Switch this deliberately registers nothing and says so, and
    // a mod that declared wiixl.net required is then refused by name at load
    // rather than loading and silently failing at its first send.
    WiiXLaunch::NetSurface::Register();

    // The framework services beyond wiixl.core: the clock, the coreinit heaps,
    // game-function resolution and runtime patching. Each is its own surface so
    // a mod declares only what it uses and a host missing one refuses it by
    // name rather than at the first call.
    WiiXLaunch::BaseSurfaces::RegisterAll();

    // Game modules register here, through the fixed name declared by whichever
    // <wiixlaunch/module.hpp> the project installed. Stage 4 calls this before
    // loading any .wxlm.
#if WIIXL_HAVE_GAME_MODULE
    WIIXL_LOG("WiiXLaunch: game module '%s'", WiiXLaunch::GameModule::kName);
    WiiXLaunch::GameModule::Register();
#else
    // Not the same as "this game has no surfaces", and it must not read as one.
    // A .wxlm needing a game surface is refused BY NAME at load, which is only
    // legible if the log already said the host has no game module at all.
    WIIXL_LOG("WiiXLaunch: no game module in this build - base surfaces only. "
              "A module requiring a game surface will be refused by name.");
#endif

    WiiXLaunch::Surface::LogRegistered();

    // --- STAGE 1: load-point validation -------------------------------------
    //
    // Site 1 of 2: the Cemu entry hook, which is the earliest point the host
    // can possibly run. Ghidra (v208 Wii U RPX) says this is NOT early enough,
    // and says so precisely rather than by guess:
    //
    //   FUN_03098928 - the function the entry hook sits on - IS the game's FS
    //   bring-up. It calls FSInit at 0x030989bc and FSAddClient at 0x030989c8.
    //   The entry hook replaces its FIRST instruction, so we are running before
    //   both. FS should therefore be absent here.
    //
    // Expected verdict: FS-ABSENT. If it comes back FS-UP-FILE-MISSING or
    // FS-USABLE, that assumption is wrong and the load point is cheaper than we
    // thought - which is exactly the kind of thing worth measuring rather than
    // reasoning about.
    WiiXLaunch::LoadPoint::Probe("entry-hook");


    // Proof the system clock is reachable: console RTC on hardware,
    // host PC clock under Cemu. Reads "unavailable" on Switch.
    char clock[20];
    WiiXLaunch::Time::FormatNow(clock, sizeof(clock));
    WIIXL_LOG("WiiXLaunch: system clock %s", clock);

#if WIIXL_BOTW_DEMO
#if WIIXL_SWITCH
    NVN::Init();
    NVN::RegisterDrawCallback(OnRender);
    // Deferred, because NVN's device does not exist yet at this point - the
    // callback fires once the game has built one. Same shape as the GX2 branch
    // below, and the reason neither creates its texture here.
    NVN::OnInitialized([]() {
        // Packaged, not raw: this header is a full NVN container, 0x200 of
        // header then the pixels. The raw entry point is for callers that
        // have only pixels - see botw.gfx.
        g_LogoTexture = NVN::CreateTexturePackaged(g_TestPicTextureBytes,
                                                   kTestPicTextureSize);
        WIIXL_LOG("WiiXLaunch: NVN logo texture initialized: %p",
                  reinterpret_cast<void*>(g_LogoTexture));
    });
#elif WIIXL_CEMU
    GX2::Init();
    GX2::RegisterDrawCallback(OnRender);
    GX2::OnInitialized([]() {
        // Under the reserved host id, like every other module's resources. The
        // host is not an exception to its own namespacing scheme - an exception
        // is how someone later decides the scheme is optional. See
        // wiixlaunch/mod_fs.hpp; a mod cannot claim an id starting with '_'.
        g_LogoTexture = GX2::LoadTexture("WiiXLaunch/mods/_host/logo.bin");
    });
// Would probably work on WUH, but I really can't be bothered unless someone finds a use for it. All you probably have to do is give it a proper texture path.
// #elif WIIXL_WIIU
//     GX2::Init();
//     GX2::RegisterDrawCallback(OnRender);
//     GX2::OnInitialized([]() {
//         g_LogoTexture = GX2::CreateTexture(g_TestpicTextureBytes, kTestpicTextureSize, kTestpicTextureWidth, kTestpicTextureHeight);
//         WIIXL_LOG("WiiXLaunch: GX2 logo texture initialized: %p", reinterpret_cast<void*>(g_LogoTexture));
//     });
#endif
#endif // WIIXL_BOTW_DEMO
}

// The Cemu bootstrap - g_CodeCaveBase, WiiXLaunch_Cemu_Relocate and the
// entry-hook stub - used to sit below here under a "NO TOUCHING" banner. It is
// framework code, not sample code, and it now lives in src/cemu/bootstrap.cpp,
// which every Cemu build compiles regardless of what this file contains.
//
// That means this file is now deletable. Everything above is a sample; an empty
// main.cpp still produces a host that boots, relocates itself and logs, using
// the weak default WiiXLaunch_Init in the bootstrap.
