// Host-side tests for WIIXL_LOG's formatter.
//
// formatter_extract.hpp is generated by extract.py straight out of
// debug_log.hpp, so these run the real FormatText rather than a copy of it.
//
// Why this exists: the payload has no libc, so debug_log.hpp carries its own
// printf, and it is the one function every platform's logging goes through.
// It cannot be exercised on a console. When it gets a conversion wrong it does
// not crash - it prints the format specifier and silently drops the argument,
// which reads as "the code under test produced nothing" and sends you looking
// in the wrong place. That is exactly what happened with %02X.

#include <cstdio>
#include <cstring>
#include <cstdint>
#include <cstdarg>

#include "formatter_extract.hpp"

static int g_failures = 0;
static int g_checks = 0;

// How many check() calls must run. If someone deletes a block of cases - or an
// #if swallows one - the count drops and this fails, instead of reporting
// success over a smaller suite. Raise it when cases are added; never lower it
// to make a build go green. See the fourth rule in docs/modules.md.
static const int kExpectedChecks = 23;

// Per-section floors as well as the total. A floor on an aggregate does not
// constrain its composition: 23 checks could all be width checks, with the
// argument-alignment regression test - the reason this harness exists - gone.
static int g_SectionBase = 0;
static const char* g_CurrentSection = "";
static int g_SectionFloorFailures = 0;

static void BeginSection(const char* name) {
    g_SectionBase = 0;
    g_CurrentSection = name;
}

static void SectionStart(const char* name);
static void SectionEnd(int atLeast);

static void check(const char* expect, const char* fmt, ...) {
    char out[256];
    va_list ap;
    va_start(ap, fmt);
    uint32_t n = WiiXLaunch::Debug::FormatText(out, sizeof(out) - 1, fmt, ap);
    va_end(ap);
    out[n] = '\0';

    ++g_checks;
    const bool ok = std::strcmp(out, expect) == 0;
    if (ok) {
        std::printf("  ok    %-22s -> \"%s\"\n", fmt, out);
    } else {
        ++g_failures;
        std::printf("  FAIL  %-22s -> \"%s\"  (expected \"%s\")\n", fmt, out, expect);
    }
}

static void SectionStart(const char* name) {
    g_SectionBase = g_checks;
    g_CurrentSection = name;
}

static void SectionEnd(int atLeast) {
    const int ran = g_checks - g_SectionBase;
    if (ran < atLeast) {
        ++g_SectionFloorFailures;
        std::printf("  FAIL  section '%s' ran %d checks, expected at least %d\n",
                    g_CurrentSection, ran, atLeast);
    }
}

int main() {
    // Unbuffered, because this binary can crash. With block-buffered stdout
    // a segfault discards everything printed so far, so the run looks like a
    // program that produced no output at all - which says nothing about where
    // it got to. Documented in docs/modules.md; it applies to every test
    // binary here, not only the one where it was first noticed.
    std::setvbuf(stdout, nullptr, _IONBF, 0);

    (void)BeginSection;
    SectionStart("width");
    std::printf("width and zero-padding (unsupported until they silently broke a hex dump):\n");
    check("05",       "%02X", 5);
    check("AB",       "%02X", 0xAB);
    check("0F 1E 2D", "%02X %02X %02X", 0x0F, 0x1E, 0x2D);
    check("0000002d", "%08x", 0x2d);
    check("  42",     "%4d", 42);
    check("0042",     "%04d", 42);
    check("-042",     "%04d", -42);
    check("00ff",     "%04x", 255);

    // A width narrower than the value must not truncate it.
    check("123456",   "%2d", 123456);

    SectionEnd(9);
    SectionStart("argument alignment");
    std::printf("\nargument alignment after a width specifier:\n");
    // The original bug consumed no argument for %02X, so everything after it
    // read the previous slot. This is the regression test for that.
    check("01 then 2", "%02X then %d", 1, 2);
    check("A=0A B=17", "A=%02X B=%d", 10, 17);

    SectionEnd(2);
    SectionStart("unchanged behaviour");
    std::printf("\nunchanged behaviour:\n");
    check("42",       "%d", 42);
    check("-42",      "%d", -42);
    check("2A",       "%X", 42);
    check("2a",       "%x", 42);
    check("1BAA54C",  "%X", 29009228);
    check("100%",     "100%%");
    check("hi 7",     "hi %d", 7);
    check("s=ok",     "s=%s", "ok");
    check("u=7",      "u=%u", 7u);

    SectionEnd(9);
    SectionStart("float precision");
    std::printf("\nfloat precision (was always supported - guard against regressing it):\n");
    check("1.5",      "%.1f", 1.5);
    check("3.14",     "%.2f", 3.14159);

    SectionEnd(2);
    SectionStart("unknown conversions");
    std::printf("\nunknown conversions are echoed, not swallowed:\n");
    check("%q",       "%q", 1);

    SectionEnd(1);
    g_failures += g_SectionFloorFailures;

    std::printf("\n%d checks, %d failures\n", g_checks, g_failures);

    if (g_checks < kExpectedChecks) {
        std::printf("FORMAT TESTS DISARMED: only %d of the expected %d checks ran.\n"
                    "A suite that shrinks silently reports success over whatever is\n"
                    "left of it.\n", g_checks, kExpectedChecks);
        return 1;
    }

    std::printf("%s (%d checks: width, argument alignment, unchanged conversions, "
                "float precision, unknown specifiers)\n",
                g_failures == 0 ? "ALL FORMAT TESTS PASS" : "FORMAT TESTS FAILED",
                g_checks);
    return g_failures != 0;
}
